flowcell: FLO-MIN106
kit: SQK-RNA001
data:
  MXG3.1: /arena/hyeshik/nanopore-201805/20180509-Mux_v5
reference_transcriptomes:
  - [hsa, refs/hsa-all.fa.gz]
  - [xla, refs/xla-all.fa.gz]
  - [cel, refs/cel-all.fa.gz]
  - [ath, refs/ath-all.fa.gz]
train_data_selection:
  min_alignment_score: 100
  min_alignment_score_ratio: 0.8333 # 5/(1+5)
  min_adapter_length: 4000
  max_adapter_length: 30000
  min_sequence_length: 200
adapter_signal_data:
  MXG3.1: /casa/hyeshik/p/nara/octopus/training/signal-cuts
train_data_transform:
  trim_adapter_length: 15000
  summarization_window_size: 20
  test_data_split: 0.2
  subsample_sizes: [2000, 5000, 10000, 9999999]
  final_trim_sizes: [500, 750, 1000, 1200, 1499]
training_parameters:
  global:
    ngpu: 2
    epochs: 50
    validation_split: 0.1
    batchsize_train: 512
    batchsize_eval: 64
    batchsize_test: 64
    optimizer: adam
    model_checkpoint_period: 10
  GRU_128_128:
    - [GRU, 128]
    - [Dropout, 0.5]
    - [GRU, 128]
    - [Dropout, 0.5]
  GRU_64_192:
    - [GRU, 64]
    - [Dropout, 0.5]
    - [GRU, 192]
    - [Dropout, 0.5]
  GRU_192_64:
    - [GRU, 192]
    - [Dropout, 0.5]
    - [GRU, 64]
    - [Dropout, 0.5]
  GRU_triple64:
    - [GRU, 64]
    - [Dropout, 0.5]
    - [GRU, 64]
    - [Dropout, 0.5]
    - [GRU, 64]
    - [Dropout, 0.5]
