flowcell: FLO-MIN106
kit: SQK-RNA001
data:
  MXG3.2: /arena/hyeshik/nanopore-data/20180622_0535_Mux_yeast/fast5
reference_transcriptomes:
  - [ath, refs/ath-all.fa.gz]
  - [hsa, refs/hsa-all.fa.gz]
  - [sce, refs/sce-all.fa.gz]
  - [cel, refs/cel-all.fa.gz]
reference_transcriptome_filtering:
  blacklist_alignment_match_length: 100
train_data_selection:
  min_alignment_score: 200
  max_2nd_alignment_score: 100
  min_alignment_score_ratio: 0.833 # 5/(1+5): factor of 5
  min_alignment_coverage: 0.5
  max_unalignable_length: 250
  min_adapter_length: 4000
  max_adapter_length: 30000
  min_sequence_length: 200
train_data_transform:
  trim_adapter_length: 300
  test_data_split: 0.2
  subsample_sizes: [50000, 180000]
  final_trim_sizes: [100, 200, 300]
training_parameters:
  global:
    ngpu: 2
    epochs: 300
    validation_split: 0.1
    batchsize_train: 1024
    batchsize_eval: 128
    batchsize_test: 512
    optimizer: adam
    model_checkpoint_period: 1
    earlystopping_min_delta: 0.001
    earlystopping_patience: 20
  GRU_128_128_05:
    - [GRU, 128]
    - [Dropout, 0.5]
    - [GRU, 128]
    - [Dropout, 0.5]
  GRU_128_128_03:
    - [GRU, 128]
    - [Dropout, 0.3]
    - [GRU, 128]
    - [Dropout, 0.3]
  GRU_64_64_03:
    - [GRU, 64]
    - [Dropout, 0.3]
    - [GRU, 64]
    - [Dropout, 0.3]
  LSTM_64_64_03:
    - [LSTM, 64]
    - [Dropout, 0.3]
    - [LSTM, 64]
    - [Dropout, 0.3]
